import Link from "next/link";
import { FileBarChart, Plus } from "lucide-react";

import DashboardHeader from "@/components/dashboard/DashboardHeader";
import EmptyState from "@/components/dashboard/EmptyState";
import PageContainer from "@/components/dashboard/PageContainer";
import Pagination from "@/components/dashboard/Pagination";
import RecordActionButton from "@/components/dashboard/RecordActionButton";
import SearchInput from "@/components/dashboard/SearchInput";
import StatusBadge from "@/components/dashboard/StatusBadge";
import { buttonVariants } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  archiveReport,
  restoreReport,
} from "@/features/reports/actions/report.actions";
import { listReports } from "@/features/reports/services/report.service";
import { requireUser } from "@/lib/auth";
import { Permissions } from "@/lib/authorization";
import { getTotalPages } from "@/lib/pagination";
import { cn, formatEnumLabel } from "@/lib/utils";

type ReportsPageProps = {
  searchParams: Promise<{ page?: string; q?: string; status?: string }>;
};

export default async function ReportsPage({ searchParams }: ReportsPageProps) {
  const user = await requireUser();
  const canManage = Permissions.manageReports(user.role);

  const params = await searchParams;
  const { reports, totalCount, page, pageSize } = await listReports(
    user.companyId,
    params
  );
  const totalPages = getTotalPages(totalCount, pageSize);
  const showingArchived = params.status === "archived";

  return (
    <PageContainer>
      <DashboardHeader
        title="Reports"
        description="Cross-module analytics and exports."
        actions={
          canManage ? (
            <Link href="/reports/new" className={cn(buttonVariants())}>
              <Plus size={16} /> Generate report
            </Link>
          ) : undefined
        }
      />

      <div className="flex items-center justify-between gap-4">
        <SearchInput
          action="/reports"
          defaultValue={params.q}
          placeholder="Search reports..."
          hiddenFields={showingArchived ? { status: "archived" } : undefined}
        />

        <div className="flex gap-2">
          <Link
            href="/reports"
            className={cn(
              buttonVariants({
                variant: showingArchived ? "outline" : "secondary",
                size: "sm",
              })
            )}
          >
            Active
          </Link>
          <Link
            href="/reports?status=archived"
            className={cn(
              buttonVariants({
                variant: showingArchived ? "secondary" : "outline",
                size: "sm",
              })
            )}
          >
            Archived
          </Link>
        </div>
      </div>

      {reports.length === 0 ? (
        <EmptyState
          icon={FileBarChart}
          title="No reports found"
          description="Try adjusting your search, or generate the first report."
        />
      ) : (
        <div className="rounded-xl border border-slate-200 bg-white">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Title</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Generated by</TableHead>
                <TableHead>Status</TableHead>
                {canManage && <TableHead className="text-right">Actions</TableHead>}
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.map((report) => (
                <TableRow key={report.id}>
                  <TableCell>
                    <Link
                      href={`/reports/${report.id}`}
                      className="font-medium hover:underline"
                    >
                      {report.title}
                    </Link>
                  </TableCell>
                  <TableCell className="text-slate-500">
                    {formatEnumLabel(report.type)}
                  </TableCell>
                  <TableCell className="text-slate-500">
                    {report.generatedBy
                      ? `${report.generatedBy.firstName} ${report.generatedBy.lastName}`
                      : "—"}
                  </TableCell>
                  <TableCell>
                    <StatusBadge
                      status={report.deletedAt ? "ARCHIVED" : report.status}
                    />
                  </TableCell>
                  {canManage && (
                    <TableCell className="text-right">
                      {report.deletedAt ? (
                        <RecordActionButton
                          id={report.id}
                          action={restoreReport}
                          label="Restore"
                          successMessage="Report restored"
                        />
                      ) : (
                        <RecordActionButton
                          id={report.id}
                          action={archiveReport}
                          label="Archive"
                          variant="destructive"
                          confirmMessage="Archive this report?"
                          successMessage="Report archived"
                        />
                      )}
                    </TableCell>
                  )}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}

      <Pagination
        page={page}
        totalPages={totalPages}
        buildHref={(targetPage) => {
          const sp = new URLSearchParams();
          if (params.q) sp.set("q", params.q);
          if (params.status) sp.set("status", params.status);
          sp.set("page", String(targetPage));
          return `/reports?${sp.toString()}`;
        }}
      />
    </PageContainer>
  );
}
