import type { Metadata } from "next";

import LegalPageShell, { LegalSection } from "@/components/legal/LegalPageShell";

export const metadata: Metadata = {
  title: { absolute: "Privacy Policy | Cloud Compass OS" },
  description: "Privacy Policy for Cloud Compass OS.",
};

/**
 * Public, unauthenticated privacy policy.
 *
 * INFORMATIONAL DRAFT — describes what this codebase actually does today,
 * conservatively. It is not a substitute for review by Cloud Sherpas's own
 * legal/business owner before this is relied on for production or App Review.
 */
export default function PrivacyPolicyPage() {
  return (
    <LegalPageShell title="Privacy Policy" lastUpdated="September 12, 2026">
      <p className="rounded-lg border border-amber-200 bg-amber-50 px-3.5 py-2.5 text-xs leading-relaxed text-amber-900">
        This policy is an informational draft describing Cloud Compass OS as currently built. It
        should be reviewed by Cloud Sherpas&apos;s business or legal owner before being relied on for
        production use or a Meta App Review submission.
      </p>

      <LegalSection heading="Introduction">
        <p>
          Cloud Compass OS (&quot;Cloud Compass,&quot; &quot;we,&quot; &quot;us&quot;) is a business and content operations
          platform used by Cloud Sherpas to manage clients, content, social media workflows,
          publishing workflows, SEO and content operations, and related business data on behalf of
          the organizations it serves. This policy describes the categories of information Cloud
          Compass may process and how that information is used.
        </p>
      </LegalSection>

      <LegalSection heading="Information We May Collect">
        <p>Depending on how Cloud Compass is used, the platform may process:</p>
        <ul className="ml-5 list-disc">
          <li>Account and workspace information for people who use Cloud Compass;</li>
          <li>Information about the clients and businesses a workspace manages;</li>
          <li>Content, files, and media created or uploaded within a workspace;</li>
          <li>Information about social media accounts a workspace chooses to connect; and</li>
          <li>Basic technical information generated by using a web application.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Account and Workspace Information">
        <p>
          To provide access to Cloud Compass, we process information such as a user&apos;s name, email
          address, role, and workspace/company association, along with records of activity taken
          within the platform (for example, what was created, updated, or scheduled, and by whom).
        </p>
      </LegalSection>

      <LegalSection heading="Client and Business Information">
        <p>
          Cloud Compass stores information about the clients and businesses a workspace manages —
          for example, business names, contacts, and project or campaign details entered by the
          workspace&apos;s own users. This information is supplied and controlled by the workspace, not
          collected directly from the client&apos;s own end customers.
        </p>
      </LegalSection>

      <LegalSection heading="Content and Files">
        <p>
          Cloud Compass stores the content a workspace creates — articles, social posts, images,
          and related files — along with metadata needed to manage and schedule that content (such
          as status, scheduling times, and revision history).
        </p>
      </LegalSection>

      <LegalSection heading="Social Media / Connected Account Data">
        <p>
          A workspace may optionally connect a social media account (for example, a Facebook Page)
          so that Cloud Compass can help manage and, where implemented, publish content on the
          workspace&apos;s behalf. When an account is connected, we may process:
        </p>
        <ul className="ml-5 list-disc">
          <li>the connected account&apos;s platform identifier;</li>
          <li>public account or Page metadata, such as its name; and</li>
          <li>an authorization credential issued by the platform that lets Cloud Compass act on the connected account&apos;s behalf until it is disconnected or the authorization expires.</li>
        </ul>
        <p>
          Connecting an account is a deliberate action taken by the workspace. Content is never
          published to a connected account without an explicit action by the workspace&apos;s own user.
        </p>
      </LegalSection>

      <LegalSection heading="How We Use Information">
        <p>We use the information described above to:</p>
        <ul className="ml-5 list-disc">
          <li>operate, maintain, and secure Cloud Compass;</li>
          <li>let a workspace manage its clients, content, and publishing workflows;</li>
          <li>maintain the connections a workspace has chosen to authorize; and</li>
          <li>diagnose problems and improve the platform.</li>
        </ul>
        <p>We do not sell personal information.</p>
      </LegalSection>

      <LegalSection heading="Third-Party Platforms">
        <p>
          Where a workspace connects a third-party platform (such as Facebook), that platform&apos;s own
          privacy policy also governs how it handles data. Cloud Compass only requests the access it
          needs to provide the features a workspace has chosen to use.
        </p>
      </LegalSection>

      <LegalSection heading="Meta/Facebook Data">
        <p>
          Where a workspace connects a Facebook account, Cloud Compass may process the Facebook
          account identifier, the identifier and public name of an authorized Facebook Page, and an
          authorization credential granted for that Page. This information is used solely to
          maintain the connection and, where a workspace chooses to use it, to publish content the
          workspace itself authors to that Page. It is not used for advertising, and it is not
          shared with unrelated third parties.
        </p>
      </LegalSection>

      <LegalSection heading="Data Security">
        <p>
          Authorization credentials for connected social accounts are stored encrypted and are not
          displayed to users beyond what is needed to confirm which account is connected. Access to
          workspace data is scoped so that one workspace&apos;s information is not exposed to another.
        </p>
      </LegalSection>

      <LegalSection heading="Data Retention">
        <p>
          Information is generally retained for as long as an account or workspace remains active,
          or as needed to provide the platform&apos;s features. Some information may be retained for a
          period afterward where necessary for legitimate business, accounting, or security
          purposes, or where required by law.
        </p>
      </LegalSection>

      <LegalSection heading="Data Sharing">
        <p>
          We do not sell personal information. Information may be shared with service providers that
          help operate Cloud Compass (for example, hosting infrastructure), with the third-party
          platforms a workspace has chosen to connect, or where required by law.
        </p>
      </LegalSection>

      <LegalSection heading="User Rights and Deletion Requests">
        <p>
          A person may request access to, correction of, or deletion of information associated with
          their use of Cloud Compass, subject to the retention needs described above. See our{" "}
          <a href="/data-deletion" className="font-medium text-[#2F4156] underline">
            Data Deletion
          </a>{" "}
          page for how to submit a request, including requests related to a connected Facebook
          account.
        </p>
      </LegalSection>

      <LegalSection heading="Cookies / Technical Information">
        <p>
          Cloud Compass uses standard web technologies (such as session cookies) necessary to keep a
          user signed in and to operate the application securely. We do not use these technologies
          for third-party advertising.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to This Policy">
        <p>
          This policy may be updated from time to time as Cloud Compass changes. The &quot;Last updated&quot;
          date above reflects the most recent revision.
        </p>
      </LegalSection>

      <LegalSection heading="Contact / Privacy Requests">
        <p>Privacy/deletion contact: [BUSINESS OWNER TO PROVIDE EMAIL]</p>
      </LegalSection>
    </LegalPageShell>
  );
}
