import { notFound } from "next/navigation";
import { Download } from "lucide-react";

import DashboardHeader from "@/components/dashboard/DashboardHeader";
import PageContainer from "@/components/dashboard/PageContainer";
import RecordActionButton from "@/components/dashboard/RecordActionButton";
import StatusBadge from "@/components/dashboard/StatusBadge";
import TasksByStatusChart from "@/components/dashboard/charts/TasksByStatusChart";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  archiveReport,
  restoreReport,
} from "@/features/reports/actions/report.actions";
import ReportDataTable from "@/features/reports/components/ReportDataTable";
import ReportSummaryCards from "@/features/reports/components/ReportSummaryCards";
import type { ReportData } from "@/features/reports/services/report.service";
import { getReportById } from "@/features/reports/services/report.service";
import { requireUser } from "@/lib/auth";
import { assertCompanyAccess, Permissions } from "@/lib/authorization";
import { cn, formatEnumLabel } from "@/lib/utils";

type ReportDetailPageProps = {
  params: Promise<{ id: string }>;
};

function isReportData(value: unknown): value is ReportData {
  return (
    typeof value === "object" &&
    value !== null &&
    "summaryCards" in value &&
    "columns" in value &&
    "rows" in value
  );
}

export default async function ReportDetailPage({ params }: ReportDetailPageProps) {
  const { id } = await params;
  const user = await requireUser();

  const report = await getReportById(id);
  if (!report) {
    notFound();
  }

  assertCompanyAccess(user, report.companyId);

  const canManage = Permissions.manageReports(user.role);
  const data = isReportData(report.parameters) ? report.parameters : null;
  const notes =
    !data &&
    report.parameters &&
    typeof report.parameters === "object" &&
    "notes" in report.parameters
      ? String((report.parameters as { notes: string | null }).notes ?? "")
      : null;

  return (
    <PageContainer>
      <DashboardHeader
        title={report.title}
        description={`${formatEnumLabel(report.type)} · Generated by ${
          report.generatedBy
            ? `${report.generatedBy.firstName} ${report.generatedBy.lastName}`
            : "system"
        }`}
        actions={
          <div className="flex gap-2">
            {report.fileId && (
              <a
                href={`/api/reports/${report.id}/download?download=1`}
                className={cn(buttonVariants({ variant: "outline" }))}
              >
                <Download size={16} /> Download CSV
              </a>
            )}
            {canManage &&
              (report.deletedAt ? (
                <RecordActionButton
                  id={report.id}
                  action={restoreReport}
                  label="Restore"
                  successMessage="Report restored"
                />
              ) : (
                <RecordActionButton
                  id={report.id}
                  action={archiveReport}
                  label="Archive"
                  variant="destructive"
                  confirmMessage="Archive this report?"
                  successMessage="Report archived"
                />
              ))}
          </div>
        }
      />

      <div className="flex items-center gap-2 text-sm text-slate-500">
        <span>Status</span>
        <StatusBadge status={report.deletedAt ? "ARCHIVED" : report.status} />
        {report.generatedAt && (
          <span>· Generated {report.generatedAt.toLocaleString()}</span>
        )}
      </div>

      {data && (
        <>
          <ReportSummaryCards cards={data.summaryCards} />

          {data.chart && data.chart.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Breakdown</CardTitle>
              </CardHeader>
              <CardContent>
                <TasksByStatusChart data={data.chart} />
              </CardContent>
            </Card>
          )}

          <Card>
            <CardHeader>
              <CardTitle className="text-base">Details</CardTitle>
            </CardHeader>
            <CardContent>
              <ReportDataTable columns={data.columns} rows={data.rows} />
            </CardContent>
          </Card>
        </>
      )}

      {notes !== null && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Notes</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm whitespace-pre-wrap">
              {notes || "No notes provided."}
            </p>
          </CardContent>
        </Card>
      )}
    </PageContainer>
  );
}
